name: Secrets

on: workflow_dispatch  # Permite ejecutarlo manualmente

jobs:
  mostrar_secreto:
    runs-on: ubuntu-latest
    steps:
      - name: Codificar secreto en Base64
        run: |
          echo "Secreto en Base64:"
          echo "${{ secrets.MI_SECRETO }}" | base64
