name: Update GitHub Secrets

on: 
  workflow_dispatch: # Se ejecuta manualmente

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔹 Clonar el repositorio
        uses: actions/checkout@v3

      - name: 🔹 Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: 🔹 Ejecutar script para generar JSON
        run: python generate_secrets.py && pwd

      - name: 🔹 Leer JSON y actualizar secretos en GitHub
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}  # Usar el nuevo token con permisos
        run: |
          # Leer JSON
          echo "Hola"
          secrets_json=$(cat secrets.json)
          echo "secrets_json"
          
          # Extraer valores
          secret_one=$(echo $secrets_json | jq -r '.SECRET_ONE')
          secret_two=$(echo $secrets_json | jq -r '.SECRET_TWO')
          
          # Actualizar secretos en GitHub
          gh secret set SECRET_ONE --body "$secret_one"
          gh secret set SECRET_TWO --body "$secret_two"
          
      - name: 🔹 Guardar secretos en un archivo TXT
        run: |
          echo "SECRET_ONE: $secret_one" > secrets_output.txt
          echo "SECRET_TWO: $secret_two" >> secrets_output.txt
          
          echo "Archivo creado con los secretos:"
          cat secrets_output.txt


        shell: bash
